(defun attiny85_pinout ()
  (insert ";      ATTiny85\n")
  (insert ";     ┌───▄───┐     \n")
  (insert ";PB5 ─┤       ├─ VCC\n")
  (insert ";PB3 ─┤       ├─ PB2\n")
  (insert ";PB4 ─┤       ├─ PB1\n")
  (insert ";GND ─┤       ├─ PB0\n")
  (insert ";     └───────┘")
  )

(defun pinout()
  (interactive)
  (let ((x (read-from-minibuffer "chip:")))
    (if (string-match-p "attiny85" (downcase x)) (attiny85_pinout))
    )
  )
